# Generated by Django 4.1 on 2023-02-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_discount_tax_order_discount_order_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
