# Generated by Django 4.1.3 on 2022-11-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=788, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
