# Generated by Django 4.1 on 2023-02-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'United States Dollar'), ('EUR', 'Euro')], default=2, max_length=3),
            preserve_default=False,
        ),
    ]
